### ISSUE TITLE
Make User registraion public/private

### ISSUE THREAD

**Issue by proggeramlug** [skelpo/UserManager#13]
A setting (like the emailconfirmation one) shoul indicate whether or not the public can register themselves. If so the users/register route needs to be protected, if not it can be public.

**Comment by calebkleveter** [comment]
Issue #9 required that registration as an admin-only route. Wouldn't that make this issue obsolete?

**Comment by proggeramlug** [comment]
We need it to be optional because in some cases the user is supposed to sign up himself/herself. 

The admin needs to be able to do that no matter what, but the in some cases users _can_ sign up.
