### ISSUE TITLE
Not clear how register (and login) works

### ISSUE THREAD

**Issue by dev4jam** [skelpo/UserManager#15]
Hey @proggeramlug, I tried to walk through register and login method implementations and came up with some questions: 

1. why register returns UserSuccessResponse which doesn't contain any session information (JWT token)
2. why login requires a request to be authenticated? usually in mobile apps client sends username/pass to get a JWT token.

**Comment by calebkleveter** [comment]
1. This is because the service requires a user confirms themselves through a link in an email that is sent to them after they register. Once they confirm themselves, then they can login and get the access token.

2. Though it looks like you need to be authenticated to login to the service, the login route is actually using the `JWTAuthenticatableMiddleware` to login the user when the route is called. The request must have `username` and `password` keys in the request body.

**Comment by dev4jam** [comment]
1. From your description, I understood that you can disable email confirmation
2. When does this authentication happen?

**Comment by calebkleveter** [comment]
Correct, [you can disable it](https://github.com/skelpo/UserManager/blob/master/Sources/App/Configuration/configure.swift#L13). However, this makes it so an existing admin user has to create accounts for people.

The authentication happens before the route handler is run in the middleware chain in [`JWTAuthenticatableMiddleware`](https://github.com/skelpo/JWTMiddleware/blob/master/Sources/JWTMiddleware/JWTAuthenticatableMiddleware.swift).

**Comment by proggeramlug** [comment]
@dev4jam Would you want users to just register without any validation? (neither email nor admin)
I'm curious if there is a use-case for this.

**Comment by dev4jam** [comment]
I have a real use-case: we are registering influencer on our platform for them. We just create an account with their email address. Not sure if admin confirmation should work in this case.

**Comment by proggeramlug** [comment]
@calebkleveter Do you think we can somehow rearrange the config so that this case would work too? I agree that there are cases for it though it's not very common anymore.

**Comment by calebkleveter** [comment]
I take a look at this.

**Comment by calebkleveter** [comment]
Fixed in https://github.com/skelpo/UserManager/commit/8f623b5ec41b0e1a6c49a627b5a14676f3edadf0
